### ISSUE TITLE
Make RangeSeekBar class open

### ISSUE THREAD

**Issue by PawelDedio** [Innovattic/range-seek-bar#1]
Hi, I like your library, but I have one problem. Common pattern is to extend external libraries class to encapsulate dependencies. Your class is not open so we cant extend it :/ Is this possible to open this class in next release?

**Comment by mirrajabi** [comment]
TODO: make the variables open, in the next release.

**Comment by gauravvermaandroid** [comment]
Hi, Nice library but i faced problem while implement more then one rangebar on same screen then can not identify which one's listener working that time.

**Comment by mirrajabi** [comment]
@gauravvermaandroid That is not related to this issue. And to avoid that scenario, just implement the interface, once per each instance of this view if they have different logics. That's the cleaner solution in most cases.

**Comment by mirrajabi** [comment]
> TODO: make the variables open, in the next release.

Will not be done.
