### ISSUE TITLE
keepMinWindow() code working twice in onTouchEvent

### ISSUE THREAD

**Issue by tjsm-dev** [Innovattic/range-seek-bar#14]
In RangeSeekBar.kt code, 
line 262 to 270 is in keepMinWindow(selectedThumb)
line 271 calls keepMinWindow(selectedThumb)
So keepMinWindow(selectedThumb) called twice.

**Comment by mirrajabi** [comment]
Fixed in 9f478813b6d0c265b98eaf9bfad9746650686987
