### ISSUE TITLE
How to set Minimum Value 

### ISSUE THREAD

**Issue by varunjain0888** [Innovattic/range-seek-bar#17]
How i can set minimum value same like max, For example, I want to set minimum 50 and max 100 so seek should start from 50 and goes to 100 but now below 50, so 50 should be the minimum start point in seek bar

**Comment by mirrajabi** [comment]
Minimum of the view cannot change and that's a design decision.
What you need to do is to change your way of calculation. 
For your case:
- You need to set the max value to 50 (i.e. max - min = 100 - 50)
- Then `onValueChanged(minThumbValue: Int, maxThumbValue: Int)` is called, you add 50 to both `minThumbValue` and `maxThumbValue`.  and you will have your result in a range between 50 and 100.

So in the callback, when `minThumbValue = 5`, you will have 55 as the output of your calculation.
