### ISSUE TITLE
Unable to attach with 2way data binding

### ISSUE THREAD

**Issue by amit7127** [Innovattic/range-seek-bar#19]
How to set data and retrieve data in Rangeseekbar using data binding?

I tried to set: 
                    app:rsb_initialMaxThumbValue="@{viewModel.maxPricePerMile}"
                    app:rsb_initialMinThumbValue="@{viewModel.minPricePerMile}"

But showing compile-time error, getter, and setter is not defined for the above attribute.

**Comment by mirrajabi** [comment]
This library doesn't support two-way data binding out of the box. if you want that, you need to write your custom binding adapters.
