### ISSUE TITLE
How to remove the gap between Min thumb and start of the track and also Max thumb and end of the track?

### ISSUE THREAD

**Issue by RockySlayer** [Innovattic/range-seek-bar#20]
Hi,

How to remove the gap between Min thumb and start of the track and also Max thumb and end of the track?

There is a margin at the start between the Min thumb and start of track and also a margin between Max thumb and end of the track. How can I remove this?

**Comment by RockySlayer** [comment]
A bit more information:

I think the issue is with trackThickness and trackSelectedThickness. When you assign values to these, it not only size up the height of the track, it also expands it's width as well.  This results a gap between the thumbs and the start and the end of the tracks. This is miss-aligning the thumbs and the values.


It would be better if we can have the thickness purely for height. I think it would be best to have separate variables to expand the width of the tracks.

**Comment by mirrajabi** [comment]
Hi @RockySlayer,
 
I can't reproduce this problem. I tried setting `trackThickness` and `trackSelectedThickness` to 10 and 15dp.
To be able to do something, I would need to know a bit more about your test scenario:
- Are you using a custom thumb drawable?
- Do you have an example+screenshot that I could check?
- Does it happen other devices with different screen sizes too?

**Comment by mirrajabi** [comment]
Turns out I was not using the latest branch. Now I can reproduce what you mentioned.

**Comment by RockySlayer** [comment]
Thanks for looking into it @mirrajabi . Hope you can provide a fix for it.

**Comment by mirrajabi** [comment]
Fixed in v1.0.8

**Comment by RockySlayer** [comment]
Hi @mirrajabi , when I update it to v1.0.8, I can't export the library and my xml can't find the Range Seekbar anymore.

**Comment by mirrajabi** [comment]
What do you mean by "export the library"? 🤔  
Do you get any errors when gradle tries to sync?  
Also maybe a "clear caches and restart" could help in case Android Studio is confused.

**Comment by RockySlayer** [comment]
I tried Invalidate caches and restart, clear project and re-build project and restarting the machine. None of them worked.

I upgraded Android studio to the latest; 4.2.2 as of now, and it worked like a charm!

Thanks @mirrajabi 

I also submitted a new enhancement request. Hope you can look into it when you get a chance :P.
