### ISSUE TITLE
RangeSeekBar.setEnable(false) does not work

### ISSUE THREAD

**Issue by RockySlayer** [Innovattic/range-seek-bar#23]
Hi,

Found another potential bug. RangeSeekBar.setEnable(false) does not work. User can still change the values using both thumbs

**Comment by mirrajabi** [comment]
Fixed in v1.0.8

**Comment by RockySlayer** [comment]
This is working now with 1.0.8. Make sure to also upgrade your Android Studio to the latest (4.2.2 at the moment)
