### ISSUE TITLE
As a user I want to set min value of range seek bar

### ISSUE THREAD

**Issue by AbdullahJaved-dev** [Innovattic/range-seek-bar#25]
I want to set the starting point of the range seek bar to 30 instead of 0, but I found no way to do it.

**Comment by RumitPatel** [comment]
I am having a same requirement. Have you got any solution?

**Comment by RumitPatel** [comment]
@AbdullahJaved-dev I am having a same requirement. Have you got any solution? I want to set minimum value to this seekbar.

**Comment by mirrajabi** [comment]
Minimum value is always 0. You can transform the output like this to change minimum to 30: `processedMin = min + 30`  
This is the common pattern for sliders.
