### ISSUE TITLE
scrollview bug

### ISSUE THREAD

**Issue by BlackDizel** [Innovattic/range-seek-bar#4]
scrollview intercept seekbar focus, and dragging work weird

**Comment by mirrajabi** [comment]
Hi, can you explain the issue more in details, please?

I've tried in a vertical `ScrollView` and it was working fine

**Comment by BlackDizel** [comment]
Try to add RangeSeekbar into scrollable scrollview and drag seekbar thumb. When touch position leave thumb, scrollview intercept touch event as scroll. Need to save focus at seekbar until touch cancelled

see method `onTouchEvent` in `AbsSeekBar` https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/widget/AbsSeekBar.java  
There `isInScrollingContainer` check exist and `shouldDelayChildPressedState` override scrollview scroll to save seekbar focus
